name: Assign reviewers from CODEOWNERS

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  contribs:
    runs-on: ubuntu-24.04
    name: Assign Reviewers from CODEOWNERS
    steps:
      - name: Assign
        uses: nrfconnect/action-codeowners-reviewers@29eaf88d1bd10daa42e481bea6c14fe6ea14bfc4
        with:
          github_token: ${{ secrets.NCS_GITHUB_TOKEN }}
