name: Assign reviewers from CODEOWNERS

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  contribs:
    runs-on: ubuntu-24.04
    name: Assign Reviewers from CODEOWNERS
    steps:
      - name: Assign
        uses: nrfconnect/action-codeowners-reviewers@2f4ac40c2a4e9535b839bc3b4d963e3c84f3278e
        with:
          github_token: ${{ secrets.NCS_NORDICBUILDER_ACTION_TOKEN }}
