name: Assign reviewers from CODEOWNERS

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  contribs:
    runs-on: ubuntu-24.04
    name: Assign Reviewers from CODEOWNERS
    steps:
      - name: Assign
        uses: nrfconnect/action-codeowners-reviewers@735af84f2ea913b4cd3edc4668bf6f9294598a9e
        with:
          github_token: ${{ secrets.NCS_GITHUB_TOKEN }}
