name: Documentation Publish

on:
  workflow_run:
    workflows: ["Documentation Build"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@bf251b5aa9c2f7eeb574a96ee720e24f801b7c11 # v6
        with:
          workflow: docbuild.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Unzip html archive
        working-directory: docs
        run: |
          OUTDIR=$(awk 'NR==1 { if ($3 ~ /^(latest|PR-[0-9]+|[0-9]+\.[0-9a-zA-Z\.\-]+)$/) print $3 }' monitor_*.txt)
          echo "OUTDIR=$OUTDIR" >> "$GITHUB_ENV"
          unzip legacy-ncs*.zip -d $OUTDIR

      - name: Obtain PR number
        working-directory: docs
        run: |
          if [ -f pr.txt ]; then
            PR=$(head -n 1 pr.txt | tr -cd '0-9')
          fi
          printf 'PR=%s\n' "$PR" >> "$GITHUB_ENV"

      - name: Upload to Azure storage
        working-directory: docs
        env:
          AZCOPY_CONCURRENCY_VALUE: 1024
        run: |
         azcopy cp $OUTDIR "${{ vars.NCS_DOC_STORAGE_URL }}?${{ secrets.NCS_DOC_SAS}}" --recursive=true

      - name: Upload Zoomin documentation
        run: |
          for file in docs/monitor*.txt; do
            if ! grep -q main ${file}; then
              echo "Not targeting main, skipping Zoomin upload"
              exit 0
            fi
          done

          # trust server
          mkdir -p ~/.ssh
          ssh-keyscan upload-v1.zoominsoftware.io >> ~/.ssh/known_hosts

          # prepare key
          echo "${{ secrets.NCS_ZOOMIN_KEY }}" | base64 -d > zoomin_key
          chmod 600 zoomin_key

          # upload files
          for file in docs/*-apis-*.zip; do
            sftp -v -i zoomin_key nordic@upload-v1.zoominsoftware.io <<EOF
            cd docs-be.nordicsemi.com/doxygen/incoming
            put ${file}
            cd ../../../nordic-be-dev.zoominsoftware.io/doxygen/incoming
            put ${file}
            quit
          EOF
          done

          for file in docs/ncs-*.zip; do
            sftp -v -i zoomin_key nordic@upload-v1.zoominsoftware.io <<EOF
            cd docs-be.nordicsemi.com/sphinx-html/incoming
            put ${file}
            cd ../../../nordic-be-dev.zoominsoftware.io/sphinx-html/incoming
            put ${file}
            quit
          EOF
          done

      - name: Find Comment
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e # v3
        id: fc
        with:
          issue-number: ${{ env.PR }}
          comment-author: 'github-actions[bot]'
          body-includes: documentation preview

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ env.PR }}
          body-path: docs/comment.txt
          edit-mode: replace
