name: Manifest
on: pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  manifest:
    runs-on: ubuntu-24.04
    name: Manifest
    steps:
      - name: Checkout the code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: ncs/nrf
          fetch-depth: 0
          persist-credentials: false

      - name: Cache pip
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: west setup
        env:
          BASE_REF: ${{ github.base_ref }}
        working-directory: ncs/nrf
        run: |
          pip3 install west
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          west init -l . || true

      - name: Manifest
        uses: zephyrproject-rtos/action-manifest@09983f53d3d878791aa37a7755ae44d695f4c1e5 # v2.0.0
        with:
          github-token: ${{ secrets.NCS_NORDICBUILDER_ACTION_TOKEN }}
          manifest-path: 'west.yml'
          checkout-path: 'ncs/nrf'
          use-tree-checkout: 'true'
          west-import-flag: 'self'
          check-impostor-commits: 'true'
          label-prefix: 'manifest-'
          verbosity-level: '1'
          labels: 'manifest'
          dnm-labels: 'DNM'
          allowed-unreachables: 'dragoon'
