name: OSS history check
on: pull_request

jobs:
  contribs:
    runs-on: ubuntu-latest
    name: Check OSS history
    steps:
      - name: Checkout sources
        uses: nordicbuilder/action-checkout-west-update@main
        with:
          git-fetch-depth: 0
          west-update-args: ''

      - name: Install extra python dependencies
        run: |
          pip3 install west
          pip3 install -r ncs/nrf/scripts/requirements-extra.txt

      - name: Set upsteam
        working-directory: ncs
        run: |
          git -C zephyr remote add upstream https://github.com/zephyrproject-rtos/zephyr

      - name: Check manifest userdata
        working-directory: ncs/nrf
        run: |
          python3 scripts/ci/check_manifest_userdata.py

      - name: Check OSS history
        uses: nrfconnect/action-oss-history@main
        with:
          workspace: 'ncs'
          args: -p zephyr -p mcuboot -p trusted-firmware-m -p hostap -p wfa-qt-control-app
