name: OSS history check
on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  contribs:
    runs-on: ubuntu-24.04
    name: Check OSS history
    steps:
      - name: Checkout sources
        uses: nrfconnect/action-checkout-west-update@main
        with:
          git-fetch-depth: 0
          west-update-args: ''

      - name: Cache pip
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: Install extra python dependencies
        run: |
          pip3 install --upgrade pip setuptools west
          pip3 install -r ncs/nrf/scripts/requirements-extra.txt

      - name: Set upstream
        working-directory: ncs
        run: |
          git -C zephyr remote add upstream https://github.com/zephyrproject-rtos/zephyr

      - name: Check manifest userdata
        working-directory: ncs/nrf
        run: |
          python3 scripts/ci/check_manifest_userdata.py

      - name: Check OSS history
        uses: nrfconnect/action-oss-history@main
        with:
          workspace: 'ncs'
          args: -p zephyr -p mcuboot -p hostap -p wfa-qt-control-app -p trusted-firmware-m
