name: OSS history check
on: pull_request

jobs:
  contribs:
    runs-on: ubuntu-latest
    name: Check OSS history
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          path: ncs/nrf
          fetch-depth: 0

      - name: Install extra python dependencies
        run: |
          pip3 install west
          pip3 install -r ncs/nrf/scripts/requirements-extra.txt

      - name: Set up the workspace
        run: |
          west init -l ncs/nrf
          cd ncs
          west update zephyr mcuboot
          git -C zephyr remote add upstream https://github.com/zephyrproject-rtos/zephyr

      - name: Check OSS history
        uses: nrfconnect/action-oss-history@main
        with:
          workspace: 'ncs'
          args: -p zephyr -p mcuboot
