name: "Close stale pull requests/issues"
on:
  schedule:
  - cron: "16 00 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: 'This pull request has been marked as stale because it has been open (more than) 30 days with no activity. Remove the stale label or add a comment saying that you would like to have the label removed otherwise this pull request will automatically be closed in 7 days. Note, that you can always re-open a closed pull request at any time.'
        stale-issue-message: 'This issue has been marked as stale because it has been open (more than) 30 days with no activity. Remove the stale label or add a comment saying that you would like to have the label removed otherwise this issue will automatically be closed in 7 days. Note, that you can always re-open a closed issue at any time.'
        days-before-stale: 30
        days-before-close: 7
        stale-issue-label: 'Stale'
        stale-pr-label: 'Stale'
